---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  tasks:
  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Verify package
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    with_items:
      - buildah

  - name: Run buildah
    shell: /usr/bin/buildah --version
    register: cmd_result

  - name: Verify binary
    assert:
      that:
        - "'command not found' not in cmd_result.stderr"
        - "'buildah version' in cmd_result.stdout"
